export const ADD_SEM = 'ADD_SEM'
export const REM_SEM = 'REM_SEM'
export const SEL_SEM = 'SEL_SEM'
export const SEL_THREAD = 'SEL_THREAD'
export const ADD_COURSE = 'ADD_COURSE'
export const REM_COURSE = 'REM_COURSE'